### ISSUE TITLE
private static List<T[]> cache = new List<T[]>(32) wrong

### ISSUE THREAD

**Issue by sonygod** [SharpKit/SharpKit-SDK#10]
private static List< T [ ] > cache = new List < T [ ] >(32);

it's seem there is an bug 

  private static List< T [ ] > cache = new List < T [ ] >(32);

 convert to js like 

    dfTempArray$1.cache = new System.Collections.Generic.List$1.ctor$$Int32(Array, 32);

throw an error

 Uncaught TypeError: undefined is not a functiondfList.js:448
 dfTempArray$1.staticDefinition.cctorjsclr.js:456
 JsCompiler.Compile_Phase2jsclr.js:406
 JsCompiler.Compile_Directjsclr.js:384
 Compile(index):13 (anonymous function)

from:
https://groups.google.com/forum/#!topic/sharpkit/6bdfRXgSNiw

**Comment by Arakis** [comment]
Hi Mr Zhan, i will check your issue within this week. Thank you for
reporting!
Am 03.03.2015 14:07 schrieb "Mr zhan" <notifications@github.com>:

**Comment by Arakis** [comment]
This bug is fixed. Take the latest version from here:
https://github.com/SharpKit/SharpKit-SDK/blob/master/Frameworks/JsClr/res/jsclr.js
